name: 'CI Failure Triage'
description: 'AI-powered CI failure triage with auto-fix and Slack notifications'
author: 'AI Toolkit'

branding:
  icon: 'alert-triangle'
  color: 'orange'

inputs:
  github_token:
    description: 'GitHub token with contents write and pull-requests write permissions'
    required: true
  fix_token:
    description: 'Token with repo scope for creating fix PRs. Falls back to github_token if not set. Required for auto_fix on pull_request events.'
    required: false
    default: ''
  slack_webhook_url:
    description: 'Slack incoming webhook URL for notifications (optional)'
    required: false
    default: ''
  auto_fix:
    description: 'Attempt to auto-fix the failure and open a draft PR (true/false)'
    required: false
    default: 'false'
  model:
    description: 'AI model to use (e.g., openai/gpt-4o)'
    required: false
    default: 'openai/gpt-4o'

runs:
  using: 'composite'
  steps:
    - name: Resolve paths
      id: paths
      shell: bash
      run: echo "triage_dir=$(realpath "${{ github.action_path }}/../automations/triage")" >> "$GITHUB_OUTPUT"

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
        cache-dependency-path: ${{ steps.paths.outputs.triage_dir }}/go.sum

    - name: Triage CI Failure
      shell: bash
      working-directory: ${{ steps.paths.outputs.triage_dir }}
      run: go run .
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        FIX_TOKEN: ${{ inputs.fix_token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        MODEL: ${{ inputs.model }}
        AUTO_FIX: ${{ inputs.auto_fix }}
